localgarage/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'mail_send' => 'printers#mail_send'

  root 'home#index'
  resources :data

  resources :printers do
    member { get :image }
  end
  
  resources :filaments
  resources :maps
  get 'printer_manipulator/index'

end

localgarage/app/models/printer.rb
class Printer < ActiveRecord::Base
  validates :address, presence: true
  # リレーション用（masa)
  # has_many :printer_filament_links
  # has_many :filaments, :through => :printer_filament_links
  # accepts_nested_attributes_for :printer_filament_links
  # accepts_nested_attributes_for :filaments
  geocoded_by :address
  after_validation :geocode
  has_many :printers_users
  has_many :users, :through => :printers_users



  # 文字検索用(masa)
  # def self.search(search)
  #   if search
  #     Printer.all
  #   else
  #     Printer.all
  #   end
  # end

  
  # def self.search(search)
  #   if search
  #     Printer.all
  #   else
  #     Printer.all
  #   end
  # end



  # リレーション用のロジック(masa)
  # def getId(material,color)
  #   f = Filament.where(["material = ? and color = ?", material, color])
  #   if f.count != 0
  #     f = f[0]
  #   else
  #     f = Filament.new
  #     f = f[0]
  #   end
  #   filament_id = f
  # end
  
end

localgarage/app/controllers/printers_controller.rb
class PrintersController < ApplicationController
  before_action :set_printer, only: [:show, :edit, :update, :destroy, :image]
  before_action :authenticate_user!, only: [:show]
  # GET /printers
  # GET /printers.json

  def index
    @printers = Printer.all
    @hash = Gmaps4rails.build_markers(@printers) do |printer,  marker|
      marker.lat printer.latitude
      marker.lng printer.longitude
      marker.infowindow printer.description
      marker.json({description: printer.description})
    end
    #文字検索用
    # @hoge = params[:search]
  end

  # GET /printers/1
  # GET /printers/1.json
  def show
    # リレーションのロジック部分
      # @printerfilamentlink = PrinterFilamentLink.new(printerfilamentlink_params)
      # p = @printer
      # @printerfilamentlink.printer_id = p.id
      # @printerfilamentlink.filament_id = filament_id

      # respond_to do |format|
      #   if @printerfilamentlink.save
      #     format.html { redirect_to @printer, notice: 'Printer was successfully created.' }
      #     format.json { render :show, status: :created, location: @printerfilamentlink }
      #   else
      #     format.html { render :new }
      #     format.json { render json: @printerfilamentlink.errors, status: :unprocessable_entity }
      #   end
      # end
      # @printer.filaments.build
      # @filament = Filament.all
  end

  # GET /printers/new
  def new
    @printer = Printer.new

    # @filament = Filament.all
    # @printer.printer_filament_links.build
    # @printer.filaments.build

  end

  # GET /printers/1/edit
  def edit
  end

  # POST /printers
  # POST /printers.json
  def create
    @printer = Printer.new(printer_params)
    @printer.user_id = current_user.id
    # upload image
    @printer.image = params[:printer][:image].read 
    # @printer.printer_id = params[:id]

    #relationship Printer & User
    u = User.find(current_user)
    u.printers << @printer

    #ここでlogicを走らせて、最終的に入力されたチェックボックスの値からfilament_idを決定する。
    #複数選択の場合も該当するfilament_id全てと新規PrinterのIDを中間テーブルにひもづけて保存すればよい。


    # @material_type = params[:material_type]
    # @color_type = params[:color_type]
    # f = Filament.where(["material = ? and color = ?", "PLA", "red"])
    # if f.count != 0
    #   f = f[0]
    # else
    #   f = Filament.new
    #   f = f[0]
    # end

    

    respond_to do |format|
      if @printer.save
        format.html { redirect_to @printer, notice: 'Printer was successfully created.' }
        format.json { render :show, status: :created, location: @printer }
      else
        format.html { render :new }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end

    
  end

  # PATCH/PUT /printers/1
  # PATCH/PUT /printers/1.json
  def update

    @printer.image = params[:printer][:image].read 
    respond_to do |format|
      if @printer.update(printer_params)
        format.html { redirect_to @printer, notice: 'Printer was successfully updated.' }
        format.json { render :show, status: :ok, location: @printer }
      else
        format.html { render :edit }
        format.json { render json: @printer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /printers/1
  # DELETE /printers/1.json
  def destroy
    @printer.destroy
    respond_to do |format|
      format.html { redirect_to printers_url, notice: 'Printer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def image
    send_data(@printer.image, disposition: :inline)
  end
  
  def mail_send
    @mail = NoticeMailer.notify_mail.deliver
    render :text => 'send finish'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def set_printer
      @printer = Printer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def printer_params
      params.require(:printer).permit(:machinemodel, :sizex, :sizey, :sizez, 
        :resolution, :location, :image_url, :condition, :user_id, :title, :description,
        :address, :latitude, :longitude,:material, :color, :printer_filament_links_attributes => [:id, :printer_id, :filament_id],
        :printer_filaments_attributes => [:id, :material, :color])
    end
    
    # def printerfilamentlink_params
    #   params.permit(:printer_id, :filament_id)
    # end
  
end

localgarage/app/helpers/printers_helper.rb
module PrintersHelper
end

localgarage/app/views/printers/_form.html.erb
<%= form_for @printer do |f| %>

<% if @printer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@printer.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% @printer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--<div class="field">
    <%= f.fields_for :printer_filament_links do |pfl| %>
      <%= pfl.label '素材' %><br>
      <%= pfl.collection_select :filament_id, @filament, :id, :material %>
    <% end %>
  </div>-->

  <!-- <table>
    <tr>
      <td>
        <%= check_box_tag "material_type[]", "ABS" %>ABS
      </td>
      <td>
        <%= check_box_tag "material_type[]", "PLA" %>PLA
      </td>
    </tr>
    <tr>
      <td>
        <%= check_box_tag "color_type[]", "red" %>red
      </td>
      <td>
        <%= check_box_tag "color_type[]", "blue" %>blue
      </td>
      <td>
        <%= check_box_tag "color_type[]", "yellow" %>yellow
      </td>
      <td>
        <%= check_box_tag "color_type[]", "green" %>green
      </td>
      <td>
        <%= check_box_tag "color_type[]", "black" %>black
      </td>
      <td>
        <%= check_box_tag "color_type[]", "white" %>white
      </td>
      <td>
        <%= check_box_tag "color_type[]", "orange" %>orange
      </td>
      <td>
        <%= check_box_tag "color_type[]", "transparent" %>transparent
      </td>
    </tr>
  </table> -->

  <div class="form-group">
    <%= f.label :image, :class => 'control-label' %>
    <div id="decorate_btn">
      <div class="decorate_label" id="list">ファイルを選択</div>
      <%= f.file_field :image, accept: "image/*", :class => 'form-control', :id=>'files' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :location_name, :class => 'control-label' %>
    <%= f.text_field :description, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :address, :class => 'control-label' %>
    <%= f.text_field :address, :class => 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :latitude, :class => 'control-label' %>
    <%= f.text_field :latitude, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :longitude, :class => 'control-label' %>
    <%= f.text_field :longitude, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :machine_name, :class => 'control-label' %>
    <%= f.text_field :machinemodel, :class => 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :resolution, :class => 'control-label' %>
    <%= f.text_field :resolution, :class => 'form-control' %>
  </div>
  <div class="form-group select_filament">
    <%= f.label :material, :class => 'control-label' %><!-- 
    <%= f.text_field :material, :class => 'form-control' %> -->
    <%= f.select(:material, options_for_select(["PLA","ABS"],["PLA","ABS"])) %>
  </div>
  
  <div class="form-group select_color">
    <%= f.label :material_color, :class => 'control-label' %><!-- 
    <%= f.text_field :color, :class => 'form-control' %> -->
    <%= f.select(:color, options_for_select(["red","blue","yellow","orange","white","black","green","transparent"],["red","blue","yellow","orange","white","black","green","transparent"])) %>
  </div>

  <!-- <div class="form-group">
    <%= f.label :condition, :class => 'control-label' %>
    <%= f.check_box :condition, :class => 'form-control' %>
  </div> -->

  <div class="form-group">
    <label class="control-label"></label>
    <%= f.submit nil, :class => 'create_printer_btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), printers_path, :class => 'cancel_btn, cancel_create_printer', 'data-no-turbolink' => true %>
  </div>
<% end %>

<script type="text/javascript">
function handleFileSelect(evt) {
    var files = evt.target.files;
    var output = [];
    console.log(files);
    if(files.length > 0){
      for (var i = 0, f; f = files[i]; i++) {
        output.push('<strong>', unescape(f.name), '</strong>');
      }
    }else{
      output.push('ファイルを選択');
    }
    document.getElementById('list').innerHTML = output.join('');
}
document.getElementById('files').addEventListener('change', handleFileSelect, false);
</script>

localgarage/app/views/printers/edit.html.erb
<%- model_class = Printer -%>
<div class="margin_top_100">
	<div class="page_header">
		<div class="new_printer_title">
		 	<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human, :default => "Edit #{model_class.model_name.human}") %></h1>
		</div>
	</div>
</div>
<div class="custom_container new_printer_content">
	<%= render :partial => 'form' %>
</div>
<div class="footer">
    <ul class="footer_links">
        <li>
            <h2>local garage</h2>
        </li>
        <li>
            <h4>Company</h4>
            <dl>
                <dd>About</dd>
                <dd>Jobs</dd>
                <dd>Blog</dd>
                <dd>Help</dd>
            </dl>
        </li>
        <li>
            <h4>Local Garage</h4>
            <dl>
                <dd>About</dd>
                <dd>Jobs</dd>
                <dd>Blog</dd>
                <dd>Help</dd>
            </dl>
        </li>
    </ul>
    <div class="social_link">
        <ul>
            <li>facebook</li>
            <li>twitter</li>
            <li>google</li>
        </ul>
    </div>
    <div class="copyright">
        <small>© Local Garage</small>
    </div>
</div>

localgarage/app/views/printers/index.html.erb
<div class="printer_list_wrapper margin_top_70" id="plwrapper">
    <div class="printer_list_left">
        <div id="map" style='height:100%;'>
        </div>

        <script type="text/javascript">
            $( document ).ready(function() {
                handler = Gmaps.build('Google');
                handler.buildMap({ provider: {},  internal: {id: 'map'}},  function(){
                    //window.alert("test");
                    markers = handler.addMarkers(<%=raw @hash.to_json %>);
                    handler.bounds.extendWith(markers);
                    handler.fitMapToBounds();
                });
            });
        </script>
        
        
    </div>
    <div class="printer_list_right">
        <div class="printer_list_container">
            <!--<div class="filter_wrapper">
                #文字検索用(masa)
                <div class="filter_column">
                    <div class="search_by_keyword">
                        <%= form_tag printers_path, :method => 'get' do %>
                            <span>素材を検索する</span>
                            <%= text_field_tag :search, params[:search], :class=>'input_text' %>
                            <%= submit_tag "Search", :material => nil, :class=>'search_btn' %>
                        <% end %>
                    </div>
                </div>
                <div class="filter_column">
                    <div class="search_printer_checkbox_wrapper">
                        <div class="checkbox_container">
                            <div>Filament</div>
                            <div class="checkbox" id="checkbox1">
                                <label><%=check_box_tag :ABS, "aps" %>ABS</label>
                            </div>
                            <div class="checkbox" id="checkbox2">
                                <label><%=check_box_tag :PLA, "pla" %>PLA</label>
                            </div>
                        </div>
                    </div>
                </div> -->
            
            <div class="printers">
                <%= content_tag_for :tr, @printers do |printer| %>
                    <% if printer.user_id %>
                    <div class="printers_table_column">
                        <div class="printers_table_column_2">
                            <table>
                                <tr>
                                    <td>
                                        <div class="printer_img">
                                            <%= link_to image_tag(image_printer_path(printer)), printer %>
                                        </div>
                                        <div class="printer_info">
                                            <h4><%= link_to printer.machinemodel, printer %></h4>
                                            <p>located at <%= printer.description %></p>
                                            
                                            <% if current_user %>
                                                <% if printer.user_id == current_user.id %>
                                                    <small><%= link_to '編集',  edit_printer_path(printer) %></small> |
                                                    <small><%= link_to '削除',  printer,  method: :delete,  data: { confirm: 'Are you sure?' } %></small>
                                                <% end %>
                                            <% end %>

                                        </div>
                                    </td>
                                </tr>
                            </table>
                        </div>
                    </div>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</div>


<style>
html{
    height: 100%;
}
body{
    height: 100%;
}
</style>


// 文字検索＋checkboxのvalueによる文字検索のスクリプト(masa)
// <script type="text/javascript">
//       $(document).ready(function(){
//           getParam();
//       });

//       function getParam() {
//           var url   = location.href;
//           if(url.indexOf("?") != -1){
//             parameters    = url.split("?");
//             params   = parameters[1].split("&");
//             var paramsArray = [];
//             for ( i = 0; i < params.length; i++ ) {
//                 neet = params[i].split("=");
//                 paramsArray.push(neet[0]);
//                 paramsArray[neet[0]] = neet[1];
//             }
//             var categoryKey = paramsArray["search"];
//             if(categoryKey == "true"){
//               document.getElementById('checkbox1').innerHTML = '<label><%=check_box_tag :true, "true", true%>利用可能</lable>';
//             }
//             if(categoryKey == "false"){
//               document.getElementById('checkbox2').innerHTML = '<label><%=check_box_tag :false, "false", true%>利用不可</lable>';
//             }
//           }else{
//             document.getElementById('checkbox1').innerHTML = '<label><%=check_box_tag :true, "true", false%>利用可能</lable>';
//             document.getElementById('checkbox2').innerHTML = '<label><%=check_box_tag :false, "false", false%>利用不可</lable>';
//           }
//       }

//       $(function(){
//           $("#checkbox1 :checkbox").click(function(){
//             if($("#checkbox1 :checked").length > 0){
//               location.href='http://localhost:3000/printers?utf8=%E2%9C%93&search=abs&commit=Search';
//             }else{
//               location.href='http://localhost:3000/printers';
//             }
//           });
//       });

//       $(function(){
//           $("#checkbox2 :checkbox").click(function(){
//             if($("#checkbox2 :checked").length > 0){
//               location.href='http://localhost:3000/printers?utf8=%E2%9C%93&search=false&commit=Search';
//             }else{
//               location.href='http://localhost:3000/printers';
//             }
//           });
//       });

//   </script>

localgarage/app/views/printers/new.html.erb
<%- model_class = Printer -%>
<div class="margin_top_100">
	<div class="page_header">
		<div class="new_printer_title">
			<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,:default => "New #{model_class.model_name.human}") %></h1>
	    </div>
	</div>
</div>
<div class="custom_container new_printer_content">
	<%= render :partial => 'form' %>
</div>
<div class="footer">
    <ul class="footer_links">
        <li>
            <h2>local garage</h2>
        </li>
        <li>
            <h4>Company</h4>
            <dl>
                <dd>About</dd>
                <dd>Jobs</dd>
                <dd>Blog</dd>
                <dd>Help</dd>
            </dl>
        </li>
        <li>
            <h4>Local Garage</h4>
            <dl>
                <dd>About</dd>
                <dd>Jobs</dd>
                <dd>Blog</dd>
                <dd>Help</dd>
            </dl>
        </li>
    </ul>
    <div class="social_link">
        <ul>
            <li>facebook</li>
            <li>twitter</li>
            <li>google</li>
        </ul>
    </div>
    <div class="copyright">
        <small>© Local Garage</small>
    </div>
</div>

localgarage/app/views/printers/show.html.erb
<%- model_class = Printer -%>
<div class="printer_info_title margin_top_100">
    <h1><%= @printer.machinemodel %></h1>
</div>

<div class="custom_container padding_top_70 printer_info_content">
    <div class="printer_info padding_top_50">
        <div class="printer_info_main_content">
            <div class="printer_img">
                <%= image_tag image_printer_path(@printer) %>
            </div>
            <div class="printer_info_wrapper">
                <div class="printer_info_column">
                    <label><strong><%= model_class.human_attribute_name(:material) %>:</strong></label>
                    <div class="content"><%= @printer.material %></div>
                </div>
                <div class="printer_info_column">
                    <label><strong><%= model_class.human_attribute_name(:color) %>:</strong></label>
                    <div class="content"><%= @printer.color%></div>
                </div>
                <div class="printer_info_column">
                    <label><strong><%= model_class.human_attribute_name(:machinemodel) %>:</strong></label>
                    <div class="content"><%= @printer.machinemodel %></div>
                </div>
                
                <div class="printer_info_column">
                    <label><strong><%= model_class.human_attribute_name(:resolution) %>:</strong></label>
                    <div class="content"><%= @printer.resolution %></div>
                </div>
                <div class="printer_info_column">
                    <label><strong><%= model_class.human_attribute_name(:location) %>:</strong></label>
                    <div class="content"><%= @printer.description %></div>
                </div>
            </div>
        </div>

    </div>
    <div class="printer_info_sidebar" id="panel">
        <div class="sidebar_container" id="panel_2">
            <% if @printer.condition == true %>
                <h4 class="use_this_printer">
                                    <%= link_to "このプリンターを使う" , data_path %></h4>
                                    <%= link_to 'Send Mail', action: "mail_send" %>
            <% else %>
                <h4 class="during_use">このプリンターは現在使用中です</h4>
            <% end %>
            <div class="form-actions">
                <div class="form_actions_column"><%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_printer_path(@printer), :class => '' %></div>
                <div class="form_actions_column"><%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    printer_path(@printer),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => '' %></div>

            </div>
            <p id="notice"><%= notice %></p>
        </div>
    </div>
        
    <div class="printer_info_back_btn">
        <%= link_to 'Back', printers_path, 'data-no-turbolink' => true %>
    </div>
</div>


<div class="footer">
    <ul class="footer_links">
        <li>
            <h2>local garage</h2>
        </li>
        <li>
            <h4>Company</h4>
            <dl>
                <dd>About</dd>
                <dd>Jobs</dd>
                <dd>Blog</dd>
                <dd>Help</dd>
            </dl>
        </li>
        <li>
            <h4>Local Garage</h4>
            <dl>
                <dd>About</dd>
                <dd>Jobs</dd>
                <dd>Blog</dd>
                <dd>Help</dd>
            </dl>
        </li>
    </ul>
    <div class="social_link">
        <ul>
            <li>facebook</li>
            <li>twitter</li>
            <li>google</li>
        </ul>
    </div>
    <div class="copyright">
        <small>© Local Garage</small>
    </div>
</div>

<script type="text/javascript">
window.onscroll = function () {
    var scrollY = document.documentElement.scrollTop || document.body.scrollTop;
    var panel = document.getElementById('panel');
    var panel2 = document.getElementById('panel_2');
    var lastY = 0;
    if(panel != null && panel2 != null) {
        if(scrollY >= 152 && scrollY > lastY){
            panel.style.top = "0";
            panel.style.marginTop = "60px";
            panel.style.position = "fixed";
        }else{
            panel.style.top = "10";
            panel.style.marginTop = "0px";
            panel.style.position = "relative";
        }
    }
    lastY = scrollY;
 }
</script>