localgarage/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  get 'mail_send' => 'printers#mail_send'

  root 'home#index'
  resources :data

  resources :printers do
    member { get :image }
  end
  
  resources :filaments
  resources :maps
  get 'printer_manipulator/index'

end

localgarage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Localgarage</title>
  <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'main' %>
  <%= csrf_meta_tags %>
</head>
<body>
    <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
    <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
    <header id="header_wrapper">
        <div class="header_custom_container">
            <div class="header_cell site_name" id="site_name">
                <h1><a data-no-turbolink="true" href="/" name="fixed_header" id="site">local garage</a></h1>
            </div>
            <div class="header_cell custom_navigator">
                <ul name="fixed_header">
                <% if user_signed_in? %>
                    <li>
                    Logged in as <strong id="current_user" onmouseover="openNav();" onmouseout="closeNav();"><%= current_user.email %></strong>
                    <div id="navlink" onmouseover="openNav();" onmouseout="closeNav();">
                        <dl>
                            <dd><%= link_to 'Edit profile',  edit_user_registration_path,  :class => 'navbar-link', :name=>'' %></dd>
                            <dd><%= link_to "Logout",  destroy_user_session_path,  method: :delete, :class=>'navbar-link', :name=>'' %></dd>
                        </dl>
                    </div>
                    </li>
                    <li class="new_printer_wrapper" id="new_printer_id">
                        <div class="new_printer">
                        <strong><%= link_to 'New Printer', new_printer_path, :class=>'new_printer_btn', 'data-no-turbolink' => true %></strong>
                        </div>
                    </li>
                <% else %>
                    <li>
                        <%= link_to "Sign up",  new_user_registration_path,  :class => 'navbar-link', :name=>'fixed_header'  %>
                        <%= link_to "Login",  new_user_session_path,  :class => 'navbar-link', :name=>'fixed_header'  %>
                    </li>
                <% end %>
                </ul>
            </div>
        </div>
    </header>

    <div class="notice">
        <% if notice %>
            <p class="alert alert-notice"><%= notice %></p>
        <% end %>
        <% if alert %>
            <p class="alert alert-error"><%= alert %></p>
        <% end %>
    </div>
    <%= yield %>
</body>
</html>